#! /bin/sh

sxhkd &
xbindkeys &
$HOME/.config/polybar/launch.sh
$HOME/.bin/wallpaper.sh compton -b &

bspc monitor -d term web code music games chat todo etc

bspc config border_width         2
bspc config window_gap           5
bspc config single_monocle	true

bspc config normal_border_color '#2A2525'
bspc config active_border_color '#494343'
bspc config focused_border_color '#494343'
bspc config bottom_padding 22

bspc config split_ratio          0.5
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a URxvt state=floating
bspc rule -a Spotify desktop='^2' state=pseudo_tiled
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

compton -b &
